version: "3.9"
services:
  sonarqube:
    image: sonarqube
    container_name: culquisonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_USERNAME = admin
      - SONAR_JDBC_PASSWORD = 123xyz

  redis:
    image: redis
    container_name: culquiredis
    ports:
      - "6379:6379"
    restart: always
    #command: redis-server --loglevel warning --requirepass redis123
